"""FrameRange"""
ARBITRATION_ID_MIN = 0x0
ARBITRATION_ID_MAX = 0x7FF
ARBITRATION_ID_MIN_EXTENDED = 0x0
ARBITRATION_ID_MAX_EXTENDED= 0x1FFFFFFF
"""StandardFrameDiagnosticDataIdentifierRange"""
DIAGNOSTICS_ID_MIN = 0x700
DIAGNOSTICS_ID_MAX = 0x7FF
"""ExpandTheRangeOfDiagnosticDataIdentifiers--ISO15765-4"""
DIAGNOSTICS_ID_MIN_EXTENDED = 0x18DA00F1
DIAGNOSTICS_ID_MAX_EXTENDED = 0x18DAFFF1
"""ScopeOfChangeInDataIdentifiers"""
BYTE_MIN = 0x00
BYTE_MAX = 0xFF
